#!/usr/bin/python3
#SPDX-FileCopyrightText:2024 Ikki Chikaraishi
#SPDX-Licence-Identifier:BSD-3-Clause
import sys

n = int(sys.stdin.read().strip())

for i in range(1, n + 1):
    for j in range(1, 10):
        print(f"{i}×{j}={i*j}", end="\t")

    print()
