#!/usr/bin/python3
#SPDX-FileCopyrightText:2024 Ikki Chikaraishi
#SPDX-Licence-Identifier:BSD-3-Clause

import sys
try:
    n = int(sys.stdin.read())

except ValueError:
    print("エラーです。数字を入力してください。", file=sys.stderr)
    sys.exit(1)

if n < 1 or n > 9:
    print("エラーです。段の数は1から9の範囲で指定してください。", file=sys.stderr)
    sys.exit(1)

for i in range(1, n + 1):
    for j in range(1, 10):
        print(f"{i}×{j}={i*j}", end="\t")

    print()
